name: Swift ARM

on:
  push:
    branches: [ master ]

jobs:

    linux-swift-armv7:
        name: Linux ARMv7
        runs-on: [self-hosted, linux, arm]
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Swift Version
          run: swift --version
        - name: Build (Debug)
          run: swift build -j 1 -c debug
        - name: Test
          run: swift test -j 1
        - name: Build (Release)
          run: swift build -j 1 -c release
